### ISSUE TITLE
n_entities NOT found

### ISSUE THREAD

**Issue by Yooz** [thomasmesnard/DeepMind-Teaching-Machines-to-Read-and-Comprehend#1]
Hi, 
I found that the variable `n_entities` is not be initially assigned. There will be a error when the class `QADataset` is constructed.

I got it ... so sorry asking such a stupid question

**Comment by nicolettiant89** [comment]
sorry i have the same problem what was the issue?

**Comment by SeekPoint** [comment]
rzai@rzai00:~/prj/DeepMind-Teaching-Machines-to-Read-and-Comprehend$ git diff
diff --git a/config/deepmind_deep_lstm.py b/config/deepmind_deep_lstm.py
index 10b5c9b..8fd05f3 100644
--- a/config/deepmind_deep_lstm.py
+++ b/config/deepmind_deep_lstm.py
@@ -3,7 +3,6 @@ from blocks.initialization import IsotropicGaussian, Constant

 from model.deep_lstm import Model

## 

 batch_size = 32
 sort_batch_count = 20

@@ -12,6 +11,7 @@ shuffle_questions = True
 concat_ctx_and_question = True
 concat_question_before = True

+n_entities = 550
 embed_size = 200

 lstm_size = [256, 256]
